#!/usr/bin/with-contenv bash
# shellcheck shell=bash

#Check to make sure the subdomain, ipv6 variable and token are set
if [ -z "${SUBDOMAINS}" ] || [ -z "${TOKEN}" ] || [ -z "${IPV6}" ]; then
    echo "Please pass both your subdomain(s), token and ipv6 setting as environment variables in your docker run command. See the readme for more details."
    sleep infinity
fi

if [[ ! -f /config/logrotate.conf ]]; then
    cp /defaults/logrotate.conf /config/logrotate.conf
    chmod 640 /config/logrotate.conf
fi

# permissions
lsiown -R abc:abc \
    /config

# run initial IP update
exec \
    s6-setuidgid abc /app/duck.sh
